version: "2"
services:
  xserver:
    build: ./
    restart: always
    privileged: true
    environment:
      ALLOWED_HOSTS: xeyes
  xeyes:
    build: ./example/xeyes
    environment:
      DISPLAY: xserver:0
    restart: always
    depends_on:
      - xserver
